apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP # NodePort
  selector:
    name: order-pod
    project: pr05
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30002
