apiVersion: v1
kind: Pod
metadata:
  name: order-pod
  labels:
    name: order-pod
    project: pr05
spec:
  containers:
  - name: order
    image: bardiayaghmaie/pr04-order:1.0
    ports:
    - containerPort: 80
