apiVersion: v1
kind: Pod
metadata:
  name: shop-pod
  labels:
    name: shop-pod
    project: pr05
spec:
  containers:
  - name: shop
    image: bardiayaghmaie/pr04-shop:1.0
    ports:
    - containerPort: 80
