apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  type: ClusterIP #NodePort
  selector:
    name: accounts-pod
    project: pr05
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30001
